#!/usr/bin/env python

import sys
import os

def main():
    try:
        home = os.environ["SICILIA"]
    except:
        home = ".."
    sys.path.insert(0,home+"/app/ctdibpm")
    import ctdibpm
    ctdibpm.main()

if __name__ == "__main__":
    main()
